repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/cristianemoyano/autopep8
    rev: 2.0.2 #master
    hooks:
      - id: autopep8
        args: [--in-place, --recursive, --aggressive, --aggressive]

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
      - id: isort
        args: [--recursive, --apply, --profile, black]